---
- name: Garantindo o download do WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraindo o WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wp_installation_dir }}"
    remote_src: yes
  become: yes

- name: Copiando o arquivo de configuracao do WordPress
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: Atribuindo novos valores ao arquivo de configuracao do WordPress
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_user_name }}" }
    - { regex: 'password_here', value: "{{ wp_user_password }}" }
    - { regex: 'localhost', value: "{{ wp_ip_database }}"}
  become: yes

- name: Copiando o arquivo de configuração do Apache pra publicar o WordPress
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - restart apache   
...