---
- name: MySQL
  hosts: database

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: Garantindo a instalação do MySQL
      apt:
        name: [mysql-server-5.7,python-mysqldb]
        state: latest
        update_cache: yes
      become: yes
    
    - name: Garantindo o banco MySQL
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: Garantindo usuario do MySQL
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL,GRANT'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '192.168.1.20'
      become: yes

    - name: Garantindo conexoes externas do MySQL
      copy:
        src: /vagrant/files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify:
        - restart mysql
      become: yes

- name: Wordpress
  hosts: wordpress

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Garantindo a instalação do Apache + PHP
      apt:
        name: [apache2,php,libapache2-mod-php,php-gd,php-ssh2,mcrypt,php-mysql]
        state: latest
        update_cache: yes
      become: yes

    - name: Garantindo o download do WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extraindo o WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: Copiando o arquivo de configuracao do WordPress
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes

    - name: Atribuindo novos valores ao arquivo de configuracao do WordPress
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: '12345' }
        - { regex: 'localhost', value: '192.168.1.30'}
      become: yes

    - name: Copiando o arquivo de configuração do Apache pra publicar o WordPress
      copy:
        src: /vagrant/files/000-default.conf
        dest: /etc/apache2/sites-available
      become: yes
      notify:
        - restart apache
...