---
- name: Testando minha playbook
  hosts: all

  tasks:
    - name: Garantindo a instalação do Apache + PHP + MySQL
      apt:
        name: [apache2,php,libapache2-mod-php,php-gd,php-ssh2,mcrypt,mysql-server-5.7,python-mysqldb,php-mysql]
        state: latest
        update_cache: yes
      become: yes

    - name: Garantindo o banco MySQL
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: Garantindo usuario do MySQL
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL,GRANT'
        state: present
      become: yes
...