Vagrant.configure("2") do |config|

    config.vm.define :ansible do |ansible|
        ansible.vm.box = "ubuntu/bionic64"
        ansible.vm.network "private_network", ip: "192.168.1.10"
        ansible.vm.provision "shell", path: "provision/ansible.sh"
        ansible.vm.provider "virtualbox" do |ansible_provider|
            ansible_provider.memory = 1024
        end
    end

    config.vm.define :wordpress do |wordpress|
        wordpress.vm.box = "ubuntu/bionic64"
        wordpress.vm.network "private_network", ip: "192.168.1.20"
        wordpress.vm.provision "shell", path: "provision/add_ssh_key.sh"
        wordpress.vm.provider "virtualbox" do |wordpress_provider|
            wordpress_provider.memory = 1024
        end
    end

    config.vm.define :database do |wordpress|
        wordpress.vm.box = "ubuntu/bionic64"
        wordpress.vm.network "private_network", ip: "192.168.1.20"
        wordpress.vm.provision "shell", path: "provision/add_ssh_key.sh"
        wordpress.vm.provider "virtualbox" do |wordpress_provider|
            wordpress_provider.memory = 2014
        end
    end

end